/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SessionControl;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.UserBO;
import static view.LoginView.userBO;

/**
 *
 * @author Ruben Hernandez
 */
public class PasswdChngWindow extends javax.swing.JFrame {

    /**
     * Creates new form PasswdChngWindow
     */
    SessionControl login = new SessionControl();
    JFrame frame;
    private static UserBO userBO;

    public PasswdChngWindow() {
        initComponents();
        userBO = LoginView.userBO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOldPasswd = new javax.swing.JLabel();
        lblNewPasswd = new javax.swing.JLabel();
        lblConfNewPasswd = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        passOldPasswd = new javax.swing.JPasswordField();
        passNewPasswd = new javax.swing.JPasswordField();
        passConfNewPasswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOldPasswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOldPasswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOldPasswd.setText("Old Password");

        lblNewPasswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewPasswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNewPasswd.setText("New Password");

        lblConfNewPasswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfNewPasswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConfNewPasswd.setText("Confirm New Password");

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfirm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConfNewPasswd)
                            .addComponent(lblNewPasswd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOldPasswd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passOldPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passNewPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passConfNewPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOldPasswd)
                    .addComponent(passOldPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPasswd)
                    .addComponent(passNewPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfNewPasswd)
                    .addComponent(passConfNewPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirm)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:

        if (passOldPasswd.getText().equals(userBO.getPassword())) 
        {
            if (passNewPasswd.getText().equals(passOldPasswd.getText())) 
            {
                JOptionPane.showMessageDialog(frame, "Por favor proporcione una contraseña diferente a la original", "Contraseña repetida", JOptionPane.ERROR_MESSAGE);
            } 
            else 
            {
                if (passNewPasswd.getText().equals(passConfNewPasswd.getText())) 
                {
                    userBO = login.changePassword(LoginView.userBO.getId(), passNewPasswd.getText());
                    if (userBO != null) 
                    {
                        JOptionPane.showMessageDialog(frame, "Se cambio la contraseña con exito!");
                        LoginView.userBO = userBO;
                        this.setVisible(false);
                        SessionWindow sess = new SessionWindow();
                        sess.setVisible(true);
                    } 
                    else 
                        System.out.println("Hubo un error al querer cambiar la contraseña.");
                }
                else 
                    JOptionPane.showMessageDialog(frame, "La contraseña que se proporciono no coincide al confirmarla", "Contraseñas no coinciden", JOptionPane.ERROR_MESSAGE);
            }

        } 
        else 
            JOptionPane.showMessageDialog(frame, "Se proporciono una contraseña equivocada", "Contraseña equivocada", JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblConfNewPasswd;
    private javax.swing.JLabel lblNewPasswd;
    private javax.swing.JLabel lblOldPasswd;
    private javax.swing.JPasswordField passConfNewPasswd;
    private javax.swing.JPasswordField passNewPasswd;
    private javax.swing.JPasswordField passOldPasswd;
    // End of variables declaration//GEN-END:variables
}
