/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.LoginView;
import static view.LoginView.userBO;
/**
 *
 * @author Ruben Hernandez
 */
public class SessionWindow extends javax.swing.JFrame 
{
    String username = LoginView.userBO.getUsername();
    /**
     * Creates new form SessionWindow
     */
    public SessionWindow() 
    {
        initComponents();
        lblWelcometxt.setText("Welcome "+ username + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcometxt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menSession = new javax.swing.JMenu();
        menIChngPasswd = new javax.swing.JMenuItem();
        menILogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcometxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWelcometxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcometxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblWelcometxt.setPreferredSize(new java.awt.Dimension(50, 20));

        menSession.setText("Session");

        menIChngPasswd.setText("Change Password");
        menIChngPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIChngPasswdActionPerformed(evt);
            }
        });
        menSession.add(menIChngPasswd);

        menILogout.setText("Logout");
        menILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menILogoutActionPerformed(evt);
            }
        });
        menSession.add(menILogout);

        jMenuBar1.add(menSession);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblWelcometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblWelcometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menIChngPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIChngPasswdActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PasswdChngWindow passch = new PasswdChngWindow();
        passch.setVisible(true);
    }//GEN-LAST:event_menIChngPasswdActionPerformed

    private void menILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menILogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_menILogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcometxt;
    private javax.swing.JMenuItem menIChngPasswd;
    private javax.swing.JMenuItem menILogout;
    private javax.swing.JMenu menSession;
    // End of variables declaration//GEN-END:variables
}
